### ISSUE TITLE
fix(lean): LawOfCosinesOQ01OQ02 + LawOfCosinesOQ01OQ01 — Mathlib 4.26.0 API drift

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/lean-genius#16238]
## Summary

Both `LawOfCosinesOQ01OQ01.lean` and `LawOfCosinesOQ01OQ02.lean` fail to compile on Mathlib 4.26.0 due to API drift. These files were marked as `verified` but now have multiple compilation errors.

### LawOfCosinesOQ01OQ01.lean (Dual Spherical Law of Cosines)
- Line 62, 70, 78: `rw [real_inner_comm ...]` pattern not found (inner product notation changed)
- Line 102: `arcLength_comm` type mismatch
- Line 119: `linarith` failed (likely due to upstream changes)
- Line 134: `div_le_one_of_le` unknown identifier (removed/renamed)

### LawOfCosinesOQ01OQ02.lean (Spherical Law of Sines — side/angle form)
- Line 54, 86, 114: `linarith` failures
- Lines 59, 65, 71, 77: `rw` pattern not found (arcLength/inner product changes)
- Line 106: unsolved goals
- Lines 136, 143, 173, 204, 224: `Invalid field 'angleA'/'angleB'` — `SphericalTriangle.angleA` dot notation fails outside defining namespace
- Lines 167, 198: `le_div_iff` unknown identifier (removed/renamed)

## Impact

This blocks `law-of-cosines-oq-01-oq-01-oq-01` (spherical sine rule generalization), which was being researched in `feature/researcher-6-spherical-sine-rule`. The proof code is mathematically complete but cannot compile until these parent files are fixed.

## Fix Hints

For `LawOfCosinesOQ01OQ02.lean`:
- Replace `t.angleA` / `t.angleB` dot notation with `SphericalTriangle.angleA t` explicit application (or move the definition to the `SphericalLawOfCosines` namespace)
- Replace `le_div_iff` with `div_le_iff` or `field_simp` approach
- Fix `linarith` failures (likely need to provide `inner_decomposition` in new form)

For `LawOfCosinesOQ01OQ01.lean`:
- Fix `real_inner_comm` rewrite pattern (inner product notation changed in Lean 4.26.0)
- Fix `div_le_one_of_le` → use `div_le_one_iff` or similar
